
spring.application.name: spring-cloud-eureka-server

---

spring.profiles: default

server.port: 8089
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    preferIpAddress: true


---

spring.profiles: localhost1
server.port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}

---

spring.profiles: localhost2
server.port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    
---

spring.profiles: localhost
server.port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost1:8081/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}