spring.profiles: default

server.port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    preferIpAddress: true


---

spring.profiles: peer1
server.port: 8081
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    preferIpAddress: true

---

spring.profiles: peer2
server.port: 8082
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    preferIpAddress: true
    
---

spring.profiles: peer3
server.port: 8083
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    preferIpAddress: true