#server:
#  ssl:
#    enabled: true
#    key-alias: localhost
#    key-store-password: spring
#    key-store: classpath:localhost.keystore
#    key-store-type: PKCS12

spring:
  security:
    user:
      name: user
      password: 123456
  zipkin:
    service:
      name: service2
