// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DailyPhone.proto

package com.elim.study.hbase.sample.protobuf;

public final class DailyPhone {
  private DailyPhone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elim.study.hbase.sample.protobuf.PhoneRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string otherNum = 1;</code>
     */
    java.lang.String getOtherNum();
    /**
     * <code>optional string otherNum = 1;</code>
     */
    com.google.protobuf.ByteString
        getOtherNumBytes();

    /**
     * <code>optional string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string keep_time = 3;</code>
     */
    java.lang.String getKeepTime();
    /**
     * <code>optional string keep_time = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeepTimeBytes();

    /**
     * <code>optional string record_time = 4;</code>
     */
    java.lang.String getRecordTime();
    /**
     * <code>optional string record_time = 4;</code>
     */
    com.google.protobuf.ByteString
        getRecordTimeBytes();
  }
  /**
   * <pre>
   * 相当于定义了一个Class叫PhoneRecord，它有四个属性，下面的等号后面的数字代表了属性的顺序。详细的语法可以参考https://github.com/protocolbuffers/protobuf
   * </pre>
   *
   * Protobuf type {@code com.elim.study.hbase.sample.protobuf.PhoneRecord}
   */
  public  static final class PhoneRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elim.study.hbase.sample.protobuf.PhoneRecord)
      PhoneRecordOrBuilder {
    // Use PhoneRecord.newBuilder() to construct.
    private PhoneRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneRecord() {
      otherNum_ = "";
      type_ = "";
      keepTime_ = "";
      recordTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PhoneRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              otherNum_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              keepTime_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              recordTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.class, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder.class);
    }

    public static final int OTHERNUM_FIELD_NUMBER = 1;
    private volatile java.lang.Object otherNum_;
    /**
     * <code>optional string otherNum = 1;</code>
     */
    public java.lang.String getOtherNum() {
      java.lang.Object ref = otherNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otherNum_ = s;
        return s;
      }
    }
    /**
     * <code>optional string otherNum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOtherNumBytes() {
      java.lang.Object ref = otherNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEEP_TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object keepTime_;
    /**
     * <code>optional string keep_time = 3;</code>
     */
    public java.lang.String getKeepTime() {
      java.lang.Object ref = keepTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keepTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string keep_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeepTimeBytes() {
      java.lang.Object ref = keepTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keepTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORD_TIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object recordTime_;
    /**
     * <code>optional string record_time = 4;</code>
     */
    public java.lang.String getRecordTime() {
      java.lang.Object ref = recordTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string record_time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRecordTimeBytes() {
      java.lang.Object ref = recordTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOtherNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, otherNum_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!getKeepTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, keepTime_);
      }
      if (!getRecordTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recordTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOtherNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, otherNum_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!getKeepTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, keepTime_);
      }
      if (!getRecordTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recordTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord)) {
        return super.equals(obj);
      }
      com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord other = (com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord) obj;

      boolean result = true;
      result = result && getOtherNum()
          .equals(other.getOtherNum());
      result = result && getType()
          .equals(other.getType());
      result = result && getKeepTime()
          .equals(other.getKeepTime());
      result = result && getRecordTime()
          .equals(other.getRecordTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + OTHERNUM_FIELD_NUMBER;
      hash = (53 * hash) + getOtherNum().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + KEEP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getKeepTime().hashCode();
      hash = (37 * hash) + RECORD_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getRecordTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 相当于定义了一个Class叫PhoneRecord，它有四个属性，下面的等号后面的数字代表了属性的顺序。详细的语法可以参考https://github.com/protocolbuffers/protobuf
     * </pre>
     *
     * Protobuf type {@code com.elim.study.hbase.sample.protobuf.PhoneRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elim.study.hbase.sample.protobuf.PhoneRecord)
        com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.class, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder.class);
      }

      // Construct using com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        otherNum_ = "";

        type_ = "";

        keepTime_ = "";

        recordTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
      }

      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord getDefaultInstanceForType() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.getDefaultInstance();
      }

      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord build() {
        com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord buildPartial() {
        com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord result = new com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord(this);
        result.otherNum_ = otherNum_;
        result.type_ = type_;
        result.keepTime_ = keepTime_;
        result.recordTime_ = recordTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord) {
          return mergeFrom((com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord other) {
        if (other == com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.getDefaultInstance()) return this;
        if (!other.getOtherNum().isEmpty()) {
          otherNum_ = other.otherNum_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getKeepTime().isEmpty()) {
          keepTime_ = other.keepTime_;
          onChanged();
        }
        if (!other.getRecordTime().isEmpty()) {
          recordTime_ = other.recordTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object otherNum_ = "";
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public java.lang.String getOtherNum() {
        java.lang.Object ref = otherNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          otherNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOtherNumBytes() {
        java.lang.Object ref = otherNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public Builder setOtherNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        otherNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public Builder clearOtherNum() {
        
        otherNum_ = getDefaultInstance().getOtherNum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public Builder setOtherNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        otherNum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object keepTime_ = "";
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public java.lang.String getKeepTime() {
        java.lang.Object ref = keepTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keepTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeepTimeBytes() {
        java.lang.Object ref = keepTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keepTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public Builder setKeepTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keepTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public Builder clearKeepTime() {
        
        keepTime_ = getDefaultInstance().getKeepTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public Builder setKeepTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keepTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordTime_ = "";
      /**
       * <code>optional string record_time = 4;</code>
       */
      public java.lang.String getRecordTime() {
        java.lang.Object ref = recordTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRecordTimeBytes() {
        java.lang.Object ref = recordTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public Builder setRecordTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public Builder clearRecordTime() {
        
        recordTime_ = getDefaultInstance().getRecordTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public Builder setRecordTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.elim.study.hbase.sample.protobuf.PhoneRecord)
    }

    // @@protoc_insertion_point(class_scope:com.elim.study.hbase.sample.protobuf.PhoneRecord)
    private static final com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord();
    }

    public static com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneRecord>
        PARSER = new com.google.protobuf.AbstractParser<PhoneRecord>() {
      public PhoneRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneRecord> getParserForType() {
      return PARSER;
    }

    public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DailyRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elim.study.hbase.sample.protobuf.DailyRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    java.util.List<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord> 
        getPhoneRecordList();
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord getPhoneRecord(int index);
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    int getPhoneRecordCount();
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    java.util.List<? extends com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder> 
        getPhoneRecordOrBuilderList();
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder getPhoneRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.elim.study.hbase.sample.protobuf.DailyRecord}
   */
  public  static final class DailyRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elim.study.hbase.sample.protobuf.DailyRecord)
      DailyRecordOrBuilder {
    // Use DailyRecord.newBuilder() to construct.
    private DailyRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DailyRecord() {
      phoneRecord_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DailyRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                phoneRecord_ = new java.util.ArrayList<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneRecord_.add(
                  input.readMessage(com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          phoneRecord_ = java.util.Collections.unmodifiableList(phoneRecord_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.class, com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.Builder.class);
    }

    public static final int PHONERECORD_FIELD_NUMBER = 1;
    private java.util.List<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord> phoneRecord_;
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    public java.util.List<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord> getPhoneRecordList() {
      return phoneRecord_;
    }
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    public java.util.List<? extends com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder> 
        getPhoneRecordOrBuilderList() {
      return phoneRecord_;
    }
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    public int getPhoneRecordCount() {
      return phoneRecord_.size();
    }
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord getPhoneRecord(int index) {
      return phoneRecord_.get(index);
    }
    /**
     * <pre>
     * 表示DailyRecord中存放了一个集合类型的PhoneRecord
     * </pre>
     *
     * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
     */
    public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder getPhoneRecordOrBuilder(
        int index) {
      return phoneRecord_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < phoneRecord_.size(); i++) {
        output.writeMessage(1, phoneRecord_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < phoneRecord_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, phoneRecord_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord)) {
        return super.equals(obj);
      }
      com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord other = (com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord) obj;

      boolean result = true;
      result = result && getPhoneRecordList()
          .equals(other.getPhoneRecordList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPhoneRecordCount() > 0) {
        hash = (37 * hash) + PHONERECORD_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneRecordList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elim.study.hbase.sample.protobuf.DailyRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elim.study.hbase.sample.protobuf.DailyRecord)
        com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.class, com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.Builder.class);
      }

      // Construct using com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhoneRecordFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (phoneRecordBuilder_ == null) {
          phoneRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          phoneRecordBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_descriptor;
      }

      public com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord getDefaultInstanceForType() {
        return com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.getDefaultInstance();
      }

      public com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord build() {
        com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord buildPartial() {
        com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord result = new com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord(this);
        int from_bitField0_ = bitField0_;
        if (phoneRecordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            phoneRecord_ = java.util.Collections.unmodifiableList(phoneRecord_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phoneRecord_ = phoneRecord_;
        } else {
          result.phoneRecord_ = phoneRecordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord) {
          return mergeFrom((com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord other) {
        if (other == com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord.getDefaultInstance()) return this;
        if (phoneRecordBuilder_ == null) {
          if (!other.phoneRecord_.isEmpty()) {
            if (phoneRecord_.isEmpty()) {
              phoneRecord_ = other.phoneRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhoneRecordIsMutable();
              phoneRecord_.addAll(other.phoneRecord_);
            }
            onChanged();
          }
        } else {
          if (!other.phoneRecord_.isEmpty()) {
            if (phoneRecordBuilder_.isEmpty()) {
              phoneRecordBuilder_.dispose();
              phoneRecordBuilder_ = null;
              phoneRecord_ = other.phoneRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phoneRecordBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneRecordFieldBuilder() : null;
            } else {
              phoneRecordBuilder_.addAllMessages(other.phoneRecord_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord> phoneRecord_ =
        java.util.Collections.emptyList();
      private void ensurePhoneRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          phoneRecord_ = new java.util.ArrayList<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord>(phoneRecord_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder> phoneRecordBuilder_;

      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public java.util.List<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord> getPhoneRecordList() {
        if (phoneRecordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phoneRecord_);
        } else {
          return phoneRecordBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public int getPhoneRecordCount() {
        if (phoneRecordBuilder_ == null) {
          return phoneRecord_.size();
        } else {
          return phoneRecordBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord getPhoneRecord(int index) {
        if (phoneRecordBuilder_ == null) {
          return phoneRecord_.get(index);
        } else {
          return phoneRecordBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder setPhoneRecord(
          int index, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord value) {
        if (phoneRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneRecordIsMutable();
          phoneRecord_.set(index, value);
          onChanged();
        } else {
          phoneRecordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder setPhoneRecord(
          int index, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder builderForValue) {
        if (phoneRecordBuilder_ == null) {
          ensurePhoneRecordIsMutable();
          phoneRecord_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneRecordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder addPhoneRecord(com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord value) {
        if (phoneRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneRecordIsMutable();
          phoneRecord_.add(value);
          onChanged();
        } else {
          phoneRecordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder addPhoneRecord(
          int index, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord value) {
        if (phoneRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneRecordIsMutable();
          phoneRecord_.add(index, value);
          onChanged();
        } else {
          phoneRecordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder addPhoneRecord(
          com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder builderForValue) {
        if (phoneRecordBuilder_ == null) {
          ensurePhoneRecordIsMutable();
          phoneRecord_.add(builderForValue.build());
          onChanged();
        } else {
          phoneRecordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder addPhoneRecord(
          int index, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder builderForValue) {
        if (phoneRecordBuilder_ == null) {
          ensurePhoneRecordIsMutable();
          phoneRecord_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneRecordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder addAllPhoneRecord(
          java.lang.Iterable<? extends com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord> values) {
        if (phoneRecordBuilder_ == null) {
          ensurePhoneRecordIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phoneRecord_);
          onChanged();
        } else {
          phoneRecordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder clearPhoneRecord() {
        if (phoneRecordBuilder_ == null) {
          phoneRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phoneRecordBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public Builder removePhoneRecord(int index) {
        if (phoneRecordBuilder_ == null) {
          ensurePhoneRecordIsMutable();
          phoneRecord_.remove(index);
          onChanged();
        } else {
          phoneRecordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder getPhoneRecordBuilder(
          int index) {
        return getPhoneRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder getPhoneRecordOrBuilder(
          int index) {
        if (phoneRecordBuilder_ == null) {
          return phoneRecord_.get(index);  } else {
          return phoneRecordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public java.util.List<? extends com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder> 
           getPhoneRecordOrBuilderList() {
        if (phoneRecordBuilder_ != null) {
          return phoneRecordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phoneRecord_);
        }
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder addPhoneRecordBuilder() {
        return getPhoneRecordFieldBuilder().addBuilder(
            com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.getDefaultInstance());
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder addPhoneRecordBuilder(
          int index) {
        return getPhoneRecordFieldBuilder().addBuilder(
            index, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.getDefaultInstance());
      }
      /**
       * <pre>
       * 表示DailyRecord中存放了一个集合类型的PhoneRecord
       * </pre>
       *
       * <code>repeated .com.elim.study.hbase.sample.protobuf.PhoneRecord phoneRecord = 1;</code>
       */
      public java.util.List<com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder> 
           getPhoneRecordBuilderList() {
        return getPhoneRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder> 
          getPhoneRecordFieldBuilder() {
        if (phoneRecordBuilder_ == null) {
          phoneRecordBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecord.Builder, com.elim.study.hbase.sample.protobuf.DailyPhone.PhoneRecordOrBuilder>(
                  phoneRecord_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          phoneRecord_ = null;
        }
        return phoneRecordBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.elim.study.hbase.sample.protobuf.DailyRecord)
    }

    // @@protoc_insertion_point(class_scope:com.elim.study.hbase.sample.protobuf.DailyRecord)
    private static final com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord();
    }

    public static com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DailyRecord>
        PARSER = new com.google.protobuf.AbstractParser<DailyRecord>() {
      public DailyRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DailyRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DailyRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DailyRecord> getParserForType() {
      return PARSER;
    }

    public com.elim.study.hbase.sample.protobuf.DailyPhone.DailyRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DailyPhone.proto\022$com.elim.study.hbase" +
      ".sample.protobuf\"U\n\013PhoneRecord\022\020\n\010other" +
      "Num\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\021\n\tkeep_time\030\003 \001" +
      "(\t\022\023\n\013record_time\030\004 \001(\t\"U\n\013DailyRecord\022F" +
      "\n\013phoneRecord\030\001 \003(\01321.com.elim.study.hba" +
      "se.sample.protobuf.PhoneRecordb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor,
        new java.lang.String[] { "OtherNum", "Type", "KeepTime", "RecordTime", });
    internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elim_study_hbase_sample_protobuf_DailyRecord_descriptor,
        new java.lang.String[] { "PhoneRecord", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
