// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Phone.proto

package com.elim.study.hbase.sample.protobuf;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elim.study.hbase.sample.protobuf.PhoneRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string otherNum = 1;</code>
     */
    java.lang.String getOtherNum();
    /**
     * <code>optional string otherNum = 1;</code>
     */
    com.google.protobuf.ByteString
        getOtherNumBytes();

    /**
     * <code>optional string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string keep_time = 3;</code>
     */
    java.lang.String getKeepTime();
    /**
     * <code>optional string keep_time = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeepTimeBytes();

    /**
     * <code>optional string record_time = 4;</code>
     */
    java.lang.String getRecordTime();
    /**
     * <code>optional string record_time = 4;</code>
     */
    com.google.protobuf.ByteString
        getRecordTimeBytes();
  }
  /**
   * Protobuf type {@code com.elim.study.hbase.sample.protobuf.PhoneRecord}
   */
  public  static final class PhoneRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elim.study.hbase.sample.protobuf.PhoneRecord)
      PhoneRecordOrBuilder {
    // Use PhoneRecord.newBuilder() to construct.
    private PhoneRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneRecord() {
      otherNum_ = "";
      type_ = "";
      keepTime_ = "";
      recordTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PhoneRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              otherNum_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              keepTime_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              recordTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elim.study.hbase.sample.protobuf.Phone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elim.study.hbase.sample.protobuf.Phone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.class, com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.Builder.class);
    }

    public static final int OTHERNUM_FIELD_NUMBER = 1;
    private volatile java.lang.Object otherNum_;
    /**
     * <code>optional string otherNum = 1;</code>
     */
    public java.lang.String getOtherNum() {
      java.lang.Object ref = otherNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otherNum_ = s;
        return s;
      }
    }
    /**
     * <code>optional string otherNum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOtherNumBytes() {
      java.lang.Object ref = otherNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEEP_TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object keepTime_;
    /**
     * <code>optional string keep_time = 3;</code>
     */
    public java.lang.String getKeepTime() {
      java.lang.Object ref = keepTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keepTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string keep_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeepTimeBytes() {
      java.lang.Object ref = keepTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keepTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORD_TIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object recordTime_;
    /**
     * <code>optional string record_time = 4;</code>
     */
    public java.lang.String getRecordTime() {
      java.lang.Object ref = recordTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string record_time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRecordTimeBytes() {
      java.lang.Object ref = recordTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOtherNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, otherNum_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!getKeepTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, keepTime_);
      }
      if (!getRecordTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recordTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOtherNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, otherNum_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!getKeepTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, keepTime_);
      }
      if (!getRecordTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recordTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord)) {
        return super.equals(obj);
      }
      com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord other = (com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord) obj;

      boolean result = true;
      result = result && getOtherNum()
          .equals(other.getOtherNum());
      result = result && getType()
          .equals(other.getType());
      result = result && getKeepTime()
          .equals(other.getKeepTime());
      result = result && getRecordTime()
          .equals(other.getRecordTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + OTHERNUM_FIELD_NUMBER;
      hash = (53 * hash) + getOtherNum().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + KEEP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getKeepTime().hashCode();
      hash = (37 * hash) + RECORD_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getRecordTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elim.study.hbase.sample.protobuf.PhoneRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elim.study.hbase.sample.protobuf.PhoneRecord)
        com.elim.study.hbase.sample.protobuf.Phone.PhoneRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elim.study.hbase.sample.protobuf.Phone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elim.study.hbase.sample.protobuf.Phone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.class, com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.Builder.class);
      }

      // Construct using com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        otherNum_ = "";

        type_ = "";

        keepTime_ = "";

        recordTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elim.study.hbase.sample.protobuf.Phone.internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
      }

      public com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord getDefaultInstanceForType() {
        return com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.getDefaultInstance();
      }

      public com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord build() {
        com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord buildPartial() {
        com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord result = new com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord(this);
        result.otherNum_ = otherNum_;
        result.type_ = type_;
        result.keepTime_ = keepTime_;
        result.recordTime_ = recordTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord) {
          return mergeFrom((com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord other) {
        if (other == com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord.getDefaultInstance()) return this;
        if (!other.getOtherNum().isEmpty()) {
          otherNum_ = other.otherNum_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getKeepTime().isEmpty()) {
          keepTime_ = other.keepTime_;
          onChanged();
        }
        if (!other.getRecordTime().isEmpty()) {
          recordTime_ = other.recordTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object otherNum_ = "";
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public java.lang.String getOtherNum() {
        java.lang.Object ref = otherNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          otherNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOtherNumBytes() {
        java.lang.Object ref = otherNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public Builder setOtherNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        otherNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public Builder clearOtherNum() {
        
        otherNum_ = getDefaultInstance().getOtherNum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string otherNum = 1;</code>
       */
      public Builder setOtherNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        otherNum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object keepTime_ = "";
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public java.lang.String getKeepTime() {
        java.lang.Object ref = keepTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keepTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeepTimeBytes() {
        java.lang.Object ref = keepTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keepTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public Builder setKeepTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keepTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public Builder clearKeepTime() {
        
        keepTime_ = getDefaultInstance().getKeepTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string keep_time = 3;</code>
       */
      public Builder setKeepTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keepTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordTime_ = "";
      /**
       * <code>optional string record_time = 4;</code>
       */
      public java.lang.String getRecordTime() {
        java.lang.Object ref = recordTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRecordTimeBytes() {
        java.lang.Object ref = recordTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public Builder setRecordTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public Builder clearRecordTime() {
        
        recordTime_ = getDefaultInstance().getRecordTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string record_time = 4;</code>
       */
      public Builder setRecordTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.elim.study.hbase.sample.protobuf.PhoneRecord)
    }

    // @@protoc_insertion_point(class_scope:com.elim.study.hbase.sample.protobuf.PhoneRecord)
    private static final com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord();
    }

    public static com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneRecord>
        PARSER = new com.google.protobuf.AbstractParser<PhoneRecord>() {
      public PhoneRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneRecord> getParserForType() {
      return PARSER;
    }

    public com.elim.study.hbase.sample.protobuf.Phone.PhoneRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Phone.proto\022$com.elim.study.hbase.samp" +
      "le.protobuf\"U\n\013PhoneRecord\022\020\n\010otherNum\030\001" +
      " \001(\t\022\014\n\004type\030\002 \001(\t\022\021\n\tkeep_time\030\003 \001(\t\022\023\n" +
      "\013record_time\030\004 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elim_study_hbase_sample_protobuf_PhoneRecord_descriptor,
        new java.lang.String[] { "OtherNum", "Type", "KeepTime", "RecordTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
